server:
  port:  8070

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: domie
    password: domie
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:ke.unify.ecommerce.kafka.OrderConfirmation

application:
  customer-url: http://localhost:8090/api/v1/customers
  product-url: http://localhost:8050/api/v1/products
  payment-url: http://localhost:8060/api/v1/payments